name: C CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Norminette
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install norminette  # Globális telepítés rendszerszinten

    - name: Run Norminette
      run: |
        norminette main.c
