name: C CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Norminette
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        python3 -m pip install --user norminette  # Telepít norminette-t a felhasználói könyvtárba

    - name: Add Norminette to PATH
      run: echo "::add-path::${HOME}/.local/bin"  # Hozzáadjuk a norminette-et a PATH-hoz

    - name: Run Norminette
      run: |
        norminette main.c
