name: C CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Norminette
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-setuptools
        sudo apt-get install -y pipx
        pipx install norminette
        pipx ensurepath

    - name: Add pipx to PATH
      run: echo "::add-path::${HOME}/.local/bin"  # Hozzáadjuk a pipx telepített programokat a PATH-hoz

    - name: Run Norminette
      run: |
        norminette main.c
