name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Check out the repository's code
    - name: Checkout code
      uses: actions/checkout@v3

    # Install dependencies like CMake and compiler tools
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make

    # Set up CMake, configure and build project
    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    # Run the tests
    - name: Run Tests
      run: |
        cd build
        ./tests
