name: Auto Tag

on: [push]

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "0.0")
          echo "::set-output name=tag::$latest_tag"

      - name: Calculate next tag
        id: calc_next_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.tag }}
          if [ "$latest_tag" = "0.0" ]; then
            next_tag="1.0"
          else
            major=$(echo $latest_tag | cut -d. -f1)
            minor=$(echo $latest_tag | cut -d. -f2)
            next_minor=$((minor+1))
            next_tag="$major.$next_minor"
          fi
          echo "::set-output name=next_tag::$next_tag"

      - name: Create new tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.calc_next_tag.outputs.next_tag }}
          git push origin ${{ steps.calc_next_tag.outputs.next_tag }}
